### ISSUE TITLE
Tag topic section in UG and include "latest link" to the Doxygen documentation

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/HDFGroup.github.io#320]
If applicable, tag the topics in the user guide with the HDF5 version introduced, similar to what is done for APIs. For instance, the VOL user guide section should be labeled as 1.14.
 
It would also be helpful if the link path to the Doxygen documentation had an optional "latest" redirect, i.e., support.hdfgroup.org/releases/hdf5/latest, that points to the v1_* path so we don't have to hard code version-specific paths in referencing documentation.

**Comment by loricooperhdf** [comment]
> If applicable, tag the topics in the user guide with the HDF5 version introduced, similar to what is done for APIs. For instance, the VOL user guide section should be labeled as 1.14.

Housekeeping discussion: Since the above changes need to be made in the HDF5 repo, should this be an issue there? 

> It would also be helpful if the link path to the Doxygen documentation had an optional "latest" redirect, i.e., support.hdfgroup.org/releases/hdf5/latest, that points to the v1_* path so we don't have to hard code version-specific paths in referencing documentation.

Definitely agree. We have an internal JIRA issue about this: https://hdfgroup.atlassian.net/browse/IWIP-484 since I believe this is something @lkurz will need to handle at the server level.

**Comment by loricooperhdf** [comment]
Woot! For the community: We will now maintain the documentation for the latest version of HDF5 at https://support.hdfgroup.org/documentation/hdf5/latest/

Unless you’re really trying to communicate about something in a particular release, use the pages under this link in PPTs, Forums, etc. so that the links will remain current as we move through releases. 

Example:
   Use this: https://support.hdfgroup.org/documentation/hdf5/latest/collective_calls.html 
   Not this: https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/documentation/doxygen/collective_calls.html
 
Closing this issue since one of Scot's issues will go in the HDF5 repo, and we fixed the other.
